name: ci
on:
  push:
    branches:
      - main

jobs:
  deploy-cryptoscool:
    runs-on: ubuntu-latest

    steps:
      - name: git pull
        uses: fifsky/ssh-action@main
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASS }}
          command: |
            cd /var/www/www-root/data/www/cryptoscool.ru
            git pull
      - name: install packages
        uses: fifsky/ssh-action@main
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASS }}
          command: |
            cd /var/www/www-root/data/www/cryptoscool.ru
            npm install
      - name: build
        uses: fifsky/ssh-action@main
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASS }}
          command: |
            cd /var/www/www-root/data/www/cryptoscool.ru
            nvm use v16.19.1
            npm run build
            pm2 restart cryptoscool
